### ISSUE TITLE
Req. 61 Discussion Questions

### ISSUE THREAD

**Issue by jlivingood** [ietf-llc/IASA2-Retrospective#6]
Question during community review: Please be prepared for a consultation on hybrid meetings prior to the start of registration for IETF-112, which may be a hybrid meeting (as well as a consultation on whether it is possible to hold in person due to COVID-19, as has occurred for meetings in 2020-2021).

Question during community review: The LLC does not know what the post-COVID-19 meeting and travel environment will be like. It seems possible that the nature or desirability of in-person meetings has been fundamentally altered and that some IETF meetings might effectively be conducted entirely online. At the same time it has also been apparent that in-person IETF meetings help to build and maintain relationships and can be a vehicle to improve collaboration and spur the development of new work. Does this mean that each future meeting should be hybrid, or that some number of meetings are hybrid and while others are online only, or something else? The IETF may wish to consider undertaking a community effort to explore these important questions further (which may be beyond the scope of the current SHMOO working group).

**Comment by jlivingood** [comment]
From the document: 
> Comments: During the IASA2 transition and bootstrapping process, we are pleased that no sponsors or funding has been lost. In addition, a new funding agreement with a novel matching program has been agreed upon with ISOC. There is also a revised sponsorship program that is successfully attracting interest and incremental funding, a revised endowment policy, a structure for online-only meeting registration fees, and a newly hired Director of Development to lead the IETF’s fundraising efforts. These are all long-term efforts that will take time to bear fruit. However, one area for action is determining what the meeting registration structure should look like for a post-COVID-19 era of hybrid meetings.

`Question during community review (Respond at https://github.com/ietf-llc/IASA2-Retrospective/issues/6): Please be prepared for a consultation on hybrid meetings prior to the start of registration for IETF-112, which may be a hybrid meeting (as well as a consultation on whether it is possible to hold in person due to COVID-19, as has occurred for meetings in 2020-2021).`

`Question during community review (Respond at https://github.com/ietf-llc/IASA2-Retrospective/issues/6): The LLC does not know what the post-COVID-19 meeting and travel environment will be like. It seems possible that the nature or desirability of in-person meetings has been fundamentally altered and that some IETF meetings might effectively be conducted entirely online. At the same time it has also been apparent that in-person IETF meetings help to build and maintain relationships and can be a vehicle to improve collaboration and spur the development of new work. Does this mean that each future meeting should be hybrid, or that some number of meetings are hybrid and while others are online only, or something else? The IETF may wish to consider undertaking a community effort to explore these important questions further (which may be beyond the scope of the current SHMOO working group).`

**Comment by jlivingood** [comment]
Personal observation: for a November meeting, registration usually opens the last week of September. That would mean that a community consultation process would need to occur in July & August so that the Board could vote to approve any new fee schedule in early September.

**Comment by petrescu** [comment]
post-covid?  As likely as a 'post-flu', or 'post-cancer' or 'post-AIDS' times.
Rather, an 'age' of mobility restrictions because of easily-spread pandemics.

In that age there are a few aspects:

- only a few people will meet in-person; what is their relationship to IETF, to be identified.
- the few in-person meetings will be tested, vaccinated and masked.  How to talk through a mask and convey face expression trustfully, remains to be explored.
- the maximum inclusion requirement for IETF participation can only be satisfied by online meetings.  What are the further characteristics of technology for online meetings, remains to be determined.

Lucky Internet is already here.

**Comment by petrescu** [comment]
Another perspective is that of sticking a head-in-the-sand, or hold the breath.  

Hold one's breath until one gets past the 4th wave.  Then open up and do meetings as before, no change.  This is minimal effort, and great success with easy planning.

The issue with this perspective is that many people applied it 3 times already, at each preceding wave, and we (or maybe just a few think so) still get stuck.

**Comment by jlivingood** [comment]
This will now be the subject of an upcoming LLC-IESG-IAB-IRTF leadership workshop. Also SMHOO is being rechartered and the LLC is planning for a potential hybrid meeting for IETF-113 in March 2022.

**Comment by petrescu** [comment]
In 5 months a hybrid meeting?  Are there initial signs prefigurating what a hybrid meeting would look like?

**Comment by jlivingood** [comment]
> In 5 months a hybrid meeting? Are there initial signs prefigurating what a hybrid meeting would look like? 

I thought I have already seen some of your comments on this on the mailing list. See https://mailarchive.ietf.org/arch/msg/ietf-announce/R-1NLlYaYrZ7ldFZ0oPQWCFKfZg/ and https://mailarchive.ietf.org/arch/msg/ietf-announce/O7fmfHzSfR-b-QlpBhCitD45iO4/ and https://mailarchive.ietf.org/arch/msg/ietf-announce/Pw1FOZyVnfyxBLADDwqdiMZW4E0/. More recently, see https://mailarchive.ietf.org/arch/browse/manycouches/?q=hybrid%20113 and https://mailarchive.ietf.org/arch/browse/ietf/?q=hybrid and https://mailarchive.ietf.org/arch/browse/admin-discuss/?q=hybrid.

**Comment by jlivingood** [comment]
More specifically, I believe Jay wrote that the LLC & Secretariat are looking at venues for up to 500 people in person and the rest participating online. The IETF LLC discussed this at our August and September board meetings in the public portion and we're hoping to hear more concrete proposals in October.

**Comment by petrescu** [comment]
Hopefully a concept of verification of the meeting site, and that of guarantees of non-spread, could be considered.

**Comment by jlivingood** [comment]
> Hopefully a concept of verification of the meeting site

The Secretariat typically has someone physically visit each potential meeting site and we anticipate them doing so here as well.

> guarantees of non-spread, could be considered.

I don't think any venue, business, organization, or person could guarantee non-spread. Certainly things such as ventilation will be a consideration though. And the ED is considering what may be required on site such as testing, quarantine, medical support, etc.

**Comment by petrescu** [comment]
> 
> 
> > Hopefully a concept of verification of the meeting site
> 
> The Secretariat typically has someone physically visit each potential meeting site and we anticipate them doing so here as well.

Well, it is good.  The visit of the Secretariat person(s) is a good thing towards helping others trust the site from several perspectives.  With respect to covid, it depends how the Secretariat person makes the visit, what questions are made, what demonstrations are performed.
> 
> > guarantees of non-spread, could be considered.
> 
> I don't think any venue, business, organization, or person could guarantee non-spread.

When I go to see a footbal game in a stadium there are some guarantees that the tribunes will not fall apart.

There should be guarantees of non-spread.  Or maybe a plan to offer such 'guarantees'.  Nobody can guarantee the future, but one can do one's best to give some form of guarantee.

> Certainly things such as ventilation will be a consideration though. And the ED is considering what may be required on site such as testing, quarantine, medical support, etc.

'ED'?

And how about the transport to the meeting?

Alex

**Comment by petrescu** [comment]
There are a few ongoing similar plannings for face-to-face meetings above a few tens of persons.

In one of them, in Brussels at end of September, I am kindly invited to attend, if I can; reference is given to an Europe URL where conditions of covid are given (fyi https://reopen.europa.eu/en ).  From that site, I deduce I should not go, because both my country and the destination country are in red.  So why people invite others to come?  Who should I trust: the event organizer inviting me, or the EU URL that tells these zones are in red but does not tell whether to go or not?  I dont know.  But I dont like to be in that situation.

Similarly, I would not like IETF organization to put me (well, the humble of me, sorry) in a similar situation.

Then there is a Hamburg event for October.  It is called ITS _World_ Congress.  The organization just announced a '2G format' (presumably to mean a 2nd generation format, not to be confused with 2G..5G; 2nd).  In it it is stated that only the 4 EU-aproved vaccines are allowed or alternatively a proof of having had the disease, and implicitely now the natural anti-bodies.   I will not be very explicit about why, but I think that is a potential mistake.

I think we should learn from the others.

In none of these two, non-spread guarantees are given, neither verifications are proposed.  The entire safety relies on the 4 vaccines  or on natural antibodies.  It is known that neither vaccines nor antibodies prevent the spread.

Alex

**Comment by jlivingood** [comment]
updating document shortly with relevant changes
